[build]
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Todas as requisições vão para a mesma função (api.js)
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200
